import type { Metadata } from "next";
import Link from "next/link";
import {
  Callout,
  ContactCard,
  KeyTerm,
  LegalPage,
  List,
  Section,
  Subheading,
} from "@/components/legal/legal-page";

export const metadata: Metadata = {
  title: "Privacy Policy | XO",
  description:
    "XO's full Privacy Policy covering data collection, LLM data routing, user rights, and retention.",
};

export default function PrivacyPolicyPage() {
  return (
    <LegalPage
      eyebrow="Legal"
      title="Privacy Policy"
      effective="April 1, 2025"
      updated="April 25, 2026"
    >
      <p>
        This Privacy Policy explains how XO Labs Inc (&quot;XO&quot;,
        &quot;we&quot;, &quot;us&quot;, or &quot;our&quot;) collects, uses,
        shares, and protects information about you when you access or use the XO
        platform and services available at{" "}
        <a
          href="https://xo.builders"
          target="_blank"
          rel="noopener noreferrer"
          className="text-[#83d63a] hover:underline"
        >
          xo.builders
        </a>{" "}
        and associated subdomains (collectively, the &quot;Services&quot;).
      </p>
      <p>
        Capitalized terms used but not defined here have the meanings given in
        our{" "}
        <Link
          href="/terms-of-service"
          className="text-[#83d63a] hover:underline"
        >
          Terms and Conditions
        </Link>
        .
      </p>
      <p>
        By using the Services, you agree to the collection and use of information
        as described in this policy. If you do not agree, do not use the
        Services.
      </p>

      <Section number={1} title="Information We Collect">
        <Subheading>1.1 Information You Provide Directly</Subheading>
        <List>
          <li>
            <KeyTerm>Account information</KeyTerm> — name, email address,
            username, and password when you register.
          </li>
          <li>
            <KeyTerm>Payment information</KeyTerm> — billing address and payment
            method details. Card data is processed and stored by our third-party
            payment processor; XO does not store full card numbers.
          </li>
          <li>
            <KeyTerm>Profile and settings</KeyTerm> — any additional details you
            add to your account profile or workspace configuration.
          </li>
          <li>
            <KeyTerm>Communications</KeyTerm> — messages you send to us via
            email, support channels, or feedback forms.
          </li>
          <li>
            <KeyTerm>Affiliate program data</KeyTerm> — if you participate in the
            affiliate program, we collect referral identifiers and payout
            information.
          </li>
        </List>

        <Subheading>1.2 Information Generated by Your Use of the Services</Subheading>
        <List>
          <li>
            <KeyTerm>Agent and Workspace data</KeyTerm> — the prompts,
            instructions, memory, and configuration you provide when building or
            deploying Agents through XO Workspaces.
          </li>
          <li>
            <KeyTerm>Deployment data</KeyTerm> — code, container configurations,
            logs, and application files you upload or deploy through XO
            Launchpad.
          </li>
          <li>
            <KeyTerm>MCP and API usage</KeyTerm> — records of API calls made
            through the XO MCP Server, including request metadata (timestamps,
            endpoint, model used) but not necessarily the full content of those
            requests depending on your plan and configuration.
          </li>
          <li>
            <KeyTerm>Usage and interaction data</KeyTerm> — pages visited,
            features used, clicks, session duration, and other behavioral signals
            within the platform.
          </li>
          <li>
            <KeyTerm>Log and diagnostic data</KeyTerm> — IP addresses, browser
            type, device identifiers, operating system, referring URLs, and error
            logs generated automatically when you access the Services.
          </li>
        </List>

        <Subheading>1.3 Information from Third Parties</Subheading>
        <List>
          <li>
            <KeyTerm>LLM Providers</KeyTerm> — when you connect a Model from an
            LLM Provider (e.g., Anthropic, OpenAI, Google, Mistral), we may
            receive metadata about API calls (such as token counts and request
            status) but we do not store the full content of prompts or
            completions unless you have explicitly enabled logging features.
          </li>
          <li>
            <KeyTerm>Third-party sign-in</KeyTerm> — if you register using a
            third-party account (e.g., GitHub, Google), we receive basic profile
            information such as name, email, and avatar from that provider.
          </li>
          <li>
            <KeyTerm>Channel integrations</KeyTerm> — when you connect Agents to
            messaging platforms such as Telegram, WhatsApp, or Slack, we may
            receive metadata about those connections (channel identifiers,
            webhook status) as needed to maintain the integration.
          </li>
        </List>
      </Section>

      <Section number={2} title="How We Use Your Information">
        <p>We use the information we collect to:</p>
        <List>
          <li>
            <KeyTerm>Provide and operate the Services</KeyTerm> — process your
            account registration, run your Agents and Deployments, and maintain
            platform functionality.
          </li>
          <li>
            <KeyTerm>Process payments</KeyTerm> — charge subscription fees,
            manage billing, and handle refunds or disputes.
          </li>
          <li>
            <KeyTerm>Improve the Services</KeyTerm> — understand how users
            interact with the platform, identify bugs, and develop new features.
          </li>
          <li>
            <KeyTerm>Communicate with you</KeyTerm> — send transactional emails
            (account confirmations, billing receipts, security alerts) and, where
            you have opted in, product updates and announcements.
          </li>
          <li>
            <KeyTerm>Support you</KeyTerm> — respond to your questions,
            troubleshoot issues, and process support requests.
          </li>
          <li>
            <KeyTerm>Enforce our Terms</KeyTerm> — detect, investigate, and
            address fraud, abuse, or violations of our Terms and Conditions.
          </li>
          <li>
            <KeyTerm>Legal compliance</KeyTerm> — meet applicable legal
            obligations, respond to lawful requests, and protect our legal
            rights.
          </li>
        </List>
        <Callout>
          We will not use your Content or Agent data to train or fine-tune AI
          models without your explicit consent.
        </Callout>
      </Section>

      <Section number={3} title="LLM Providers and Your Data">
        <p>
          XO enables you to bring and connect your own LLM Provider (e.g.,
          Anthropic Claude, OpenAI GPT, Google Gemini, Meta Llama, Mistral). When
          you do so:
        </p>
        <List>
          <li>
            <KeyTerm>Data routing</KeyTerm> — prompts, instructions, and context
            you configure are transmitted to your chosen LLM Provider on your
            behalf. XO acts as infrastructure for that transmission; we do not
            independently process or retain the content of those transmissions
            beyond what is necessary to deliver the response to you, unless
            logging is explicitly enabled.
          </li>
          <li>
            <KeyTerm>LLM Provider data practices</KeyTerm> — each LLM Provider
            has its own privacy policy and data handling practices, including
            policies on whether they log, retain, review, or use your inputs for
            model improvement. XO has no control over and is not responsible for
            how LLM Providers handle data you send to them. You should review the
            privacy policy of each LLM Provider you connect before use.
          </li>
          <li>
            <KeyTerm>API key storage</KeyTerm> — if you store LLM Provider API
            keys within the Services, we encrypt them at rest. However, you are
            responsible for the security of your keys and for revoking them if
            compromised.
          </li>
          <li>
            <KeyTerm>Your data obligations</KeyTerm> — if you are sending
            personal data about your end users through a Model via XO, you are
            responsible for ensuring you have the appropriate legal basis to do
            so and that you have disclosed this in your own privacy notices.
          </li>
        </List>
      </Section>

      <Section number={4} title="How We Share Your Information">
        <p>
          We do not sell your personal data. We share information only as
          described below.
        </p>
        <List>
          <li>
            <KeyTerm>Service providers.</KeyTerm> We share data with vendors who
            help us operate the Services, including cloud infrastructure
            providers, payment processors, email delivery services, analytics
            platforms, and customer support tools. These vendors are bound by
            data processing agreements and may only use your data to provide
            services to us.
          </li>
          <li>
            <KeyTerm>LLM Providers.</KeyTerm> As described in Section 3, data you
            route through the Services to an LLM Provider is shared with that
            provider per your configuration. This sharing is at your direction.
          </li>
          <li>
            <KeyTerm>Third-party integrations.</KeyTerm> When you connect
            Third-Party Services (Telegram, WhatsApp, Slack, GitHub, etc.),
            information necessary to operate those integrations is shared with
            the relevant platforms.
          </li>
          <li>
            <KeyTerm>Business transfers.</KeyTerm> If XO is involved in a merger,
            acquisition, financing, or sale of assets, your information may be
            transferred as part of that transaction. We will provide notice
            before your information is subject to a materially different privacy
            policy.
          </li>
          <li>
            <KeyTerm>Legal requirements.</KeyTerm> We may disclose information if
            required to do so by law, regulation, legal process, or governmental
            authority, or if we believe disclosure is necessary to protect the
            rights, property, or safety of XO, our users, or the public.
          </li>
          <li>
            <KeyTerm>With your consent.</KeyTerm> We may share your information
            for purposes not listed here with your explicit consent.
          </li>
        </List>
      </Section>

      <Section number={5} title="Cookies and Tracking Technologies">
        <p>
          We use cookies and similar technologies (local storage, session
          storage, pixels) to:
        </p>
        <List>
          <li>Keep you logged in and maintain your session.</li>
          <li>Remember your preferences and settings.</li>
          <li>Analyze usage patterns and platform performance.</li>
          <li>Serve and measure the effectiveness of any communications.</li>
        </List>
        <p>
          You can control cookies through your browser settings. Disabling
          certain cookies may affect the functionality of the Services. We do not
          currently respond to &quot;Do Not Track&quot; browser signals, as there
          is no industry-standard protocol for doing so.
        </p>
      </Section>

      <Section number={6} title="Data Retention">
        <p>
          We retain your information for as long as your account is active or as
          needed to provide the Services. Specifically:
        </p>
        <List>
          <li>
            <KeyTerm>Account data</KeyTerm> is retained for the duration of your
            account and for up to 90 days following account closure, after which
            it is deleted or anonymized.
          </li>
          <li>
            <KeyTerm>Deployment and Agent data</KeyTerm> (logs, container data,
            workspace configurations) may be deleted upon account closure or plan
            expiry. You are responsible for exporting data you need before
            closing your account.
          </li>
          <li>
            <KeyTerm>Billing records</KeyTerm> are retained for as long as
            required by applicable tax and financial regulations (typically 7
            years).
          </li>
          <li>
            <KeyTerm>Anonymized or aggregated data</KeyTerm> may be retained
            indefinitely for analytical purposes and does not identify you
            individually.
          </li>
        </List>
      </Section>

      <Section number={7} title="Security">
        <p>
          We implement industry-standard technical and organizational measures to
          protect your information, including encryption in transit (TLS) and at
          rest, access controls, and regular security reviews. However, no method
          of transmission or storage is 100% secure. You are responsible for
          maintaining the security of your account credentials and API keys.
          Notify us immediately at{" "}
          <a
            href="mailto:hello@xo.builders"
            className="text-[#83d63a] hover:underline"
          >
            hello@xo.builders
          </a>{" "}
          if you believe your account has been compromised.
        </p>
      </Section>

      <Section number={8} title="Your Rights">
        <p>
          Depending on where you are located, you may have the following rights
          with respect to your personal data:
        </p>
        <List>
          <li>
            <KeyTerm>Access</KeyTerm> — request a copy of the personal data we
            hold about you.
          </li>
          <li>
            <KeyTerm>Correction</KeyTerm> — request that we correct inaccurate or
            incomplete data.
          </li>
          <li>
            <KeyTerm>Deletion</KeyTerm> — request that we delete your personal
            data, subject to legal retention obligations.
          </li>
          <li>
            <KeyTerm>Portability</KeyTerm> — request a machine-readable export of
            your data.
          </li>
          <li>
            <KeyTerm>Objection / Restriction</KeyTerm> — object to or request
            restriction of certain processing activities.
          </li>
          <li>
            <KeyTerm>Withdraw consent</KeyTerm> — where processing is based on
            consent, withdraw it at any time without affecting the lawfulness of
            prior processing.
          </li>
        </List>

        <Subheading>EEA, UK, and Switzerland</Subheading>
        <p>
          If you are located in the European Economic Area, United Kingdom, or
          Switzerland, XO processes your data as a data controller. The legal
          bases for processing include contract performance, legitimate
          interests, legal obligation, and consent. You may lodge a complaint
          with your local data protection authority.
        </p>

        <Subheading>California Residents (CCPA/CPRA)</Subheading>
        <p>
          California residents have the right to know what personal information
          we collect and how it is used, to delete personal information, to
          correct inaccurate personal information, to opt out of the sale or
          sharing of personal information (we do not sell personal information),
          and to non-discrimination for exercising these rights. To exercise your
          rights, contact us at{" "}
          <a
            href="mailto:hello@xo.builders"
            className="text-[#83d63a] hover:underline"
          >
            hello@xo.builders
          </a>
          .
        </p>

        <p>
          To exercise any of the above rights, submit a request to{" "}
          <a
            href="mailto:hello@xo.builders"
            className="text-[#83d63a] hover:underline"
          >
            hello@xo.builders
          </a>
          . We will respond within the timeframe required by applicable law. We
          may need to verify your identity before fulfilling a request.
        </p>
      </Section>

      <Section number={9} title="Children's Privacy">
        <p>
          The Services are not directed to individuals under the age of 18. We do
          not knowingly collect personal information from children under 18. If
          you believe we have inadvertently collected such information, contact
          us at{" "}
          <a
            href="mailto:hello@xo.builders"
            className="text-[#83d63a] hover:underline"
          >
            hello@xo.builders
          </a>{" "}
          and we will take prompt steps to delete it.
        </p>
      </Section>

      <Section number={10} title="International Data Transfers">
        <p>
          XO is based in the United States. If you access the Services from
          outside the United States, your information may be transferred to,
          stored, and processed in the United States or other countries where our
          service providers operate. We take steps to ensure that cross-border
          transfers comply with applicable data protection laws, including
          through the use of standard contractual clauses where required.
        </p>
      </Section>

      <Section number={11} title="Links to Other Services">
        <p>
          The Services may contain links to third-party websites, tools, and
          platforms. This Privacy Policy applies only to the Services operated by
          XO. We are not responsible for the privacy practices of any third-party
          service and encourage you to review their privacy policies before
          sharing information with them.
        </p>
      </Section>

      <Section number={12} title="Changes to This Policy">
        <p>
          We may update this Privacy Policy from time to time. If we make
          material changes, we will notify you by email or by posting a notice on
          the platform before the changes take effect. Your continued use of the
          Services after the effective date of the updated policy constitutes
          acceptance of the changes. If you do not agree, you must stop using the
          Services.
        </p>
      </Section>

      <Section number={13} title="Contact">
        <p>
          For questions, requests, or concerns about this Privacy Policy or your
          personal data, contact us at:
        </p>
        <ContactCard />
        <Callout>
          These practices sit alongside our{" "}
          <Link
            href="/terms-of-service"
            className="text-[#83d63a] hover:underline"
          >
            Terms of Service
          </Link>
          , which govern your use of the platform.
        </Callout>
      </Section>
    </LegalPage>
  );
}
