/* Generated from the whitepaper's extracted text: real tokens with
   approximate occurrence counts. Positions and vectors are simulated. */

export type PaperToken = { t: string; n: number; c: ClusterKey };
export type ClusterKey = "minting" | "verification" | "cost" | "metrics" | "energy" | "economics" | "gaming" | "numbers";

export const clusterLabels: Record<ClusterKey, string> = {
  "minting": "Minting",
  "verification": "Verification",
  "cost": "The cost meter",
  "metrics": "Portfolio metrics",
  "energy": "The energy bridge",
  "economics": "Economics",
  "gaming": "Gaming the unit",
  "numbers": "The worked numbers"
};

export const paperTokens: PaperToken[] = [
  { t: "quirq", n: 47, c: "minting" },
  { t: "quirqs", n: 38, c: "minting" },
  { t: "mint", n: 12, c: "minting" },
  { t: "minted", n: 11, c: "minting" },
  { t: "budget", n: 25, c: "minting" },
  { t: "potential", n: 4, c: "minting" },
  { t: "outcome", n: 14, c: "minting" },
  { t: "owner", n: 15, c: "minting" },
  { t: "value", n: 26, c: "minting" },
  { t: "denominated", n: 2, c: "minting" },
  { t: "delivered", n: 12, c: "minting" },
  { t: "verification", n: 13, c: "verification" },
  { t: "verified", n: 10, c: "verification" },
  { t: "snapshot", n: 4, c: "verification" },
  { t: "state", n: 21, c: "verification" },
  { t: "check", n: 18, c: "verification" },
  { t: "checks", n: 15, c: "verification" },
  { t: "ledger", n: 26, c: "verification" },
  { t: "completion", n: 5, c: "verification" },
  { t: "scored", n: 1, c: "verification" },
  { t: "audit", n: 13, c: "verification" },
  { t: "tamper-evident", n: 2, c: "verification" },
  { t: "definition of done", n: 5, c: "verification" },
  { t: "token", n: 30, c: "cost" },
  { t: "tokens", n: 17, c: "cost" },
  { t: "inference", n: 11, c: "cost" },
  { t: "compute", n: 9, c: "cost" },
  { t: "gpu", n: 2, c: "cost" },
  { t: "cpu", n: 3, c: "cost" },
  { t: "api", n: 7, c: "cost" },
  { t: "storage", n: 4, c: "cost" },
  { t: "amortization", n: 1, c: "cost" },
  { t: "intervention", n: 8, c: "cost" },
  { t: "spend", n: 6, c: "cost" },
  { t: "meter", n: 19, c: "cost" },
  { t: "all-in", n: 11, c: "cost" },
  { t: "qer", n: 15, c: "metrics" },
  { t: "velocity", n: 4, c: "metrics" },
  { t: "margin", n: 4, c: "metrics" },
  { t: "multiple", n: 1, c: "metrics" },
  { t: "ratio", n: 9, c: "metrics" },
  { t: "trajectory", n: 5, c: "metrics" },
  { t: "trend", n: 8, c: "metrics" },
  { t: "rate", n: 8, c: "metrics" },
  { t: "efficiency", n: 5, c: "metrics" },
  { t: "cost per quirq", n: 7, c: "metrics" },
  { t: "energy", n: 15, c: "energy" },
  { t: "carbon", n: 9, c: "energy" },
  { t: "kwh", n: 5, c: "energy" },
  { t: "electricity", n: 2, c: "energy" },
  { t: "watt", n: 1, c: "energy" },
  { t: "co2", n: 4, c: "energy" },
  { t: "joules", n: 1, c: "energy" },
  { t: "kilowatt-hour", n: 2, c: "energy" },
  { t: "contract", n: 6, c: "economics" },
  { t: "incentive", n: 2, c: "economics" },
  { t: "economy", n: 3, c: "economics" },
  { t: "price", n: 7, c: "economics" },
  { t: "dollar", n: 10, c: "economics" },
  { t: "business", n: 8, c: "economics" },
  { t: "cfo", n: 1, c: "economics" },
  { t: "roi", n: 2, c: "economics" },
  { t: "denominator", n: 2, c: "economics" },
  { t: "unit of account", n: 7, c: "economics" },
  { t: "accounting", n: 12, c: "economics" },
  { t: "willingness to pay", n: 2, c: "economics" },
  { t: "goodhart", n: 2, c: "gaming" },
  { t: "gaming", n: 3, c: "gaming" },
  { t: "inflation", n: 7, c: "gaming" },
  { t: "attack", n: 2, c: "gaming" },
  { t: "gamed", n: 1, c: "gaming" },
  { t: "farmed", n: 1, c: "gaming" },
  { t: "target", n: 1, c: "gaming" },
  { t: "15,770", n: 1, c: "numbers" },
  { t: "38,000", n: 2, c: "numbers" },
  { t: "2,100", n: 1, c: "numbers" },
  { t: "4,800", n: 1, c: "numbers" },
  { t: "3.1", n: 3, c: "numbers" },
  { t: "5.6", n: 5, c: "numbers" },
  { t: "0.128", n: 2, c: "numbers" },
  { t: "0.032", n: 1, c: "numbers" },
  { t: "$4", n: 3, c: "numbers" },
  { t: "31", n: 1, c: "numbers" },
  { t: "18.1%", n: 1, c: "numbers" },
  { t: "11.4%", n: 1, c: "numbers" },
  { t: "+81%", n: 1, c: "numbers" },
  { t: "+83%", n: 1, c: "numbers" },
  { t: "312", n: 1, c: "numbers" },
];
